### ISSUE TITLE
Dark theme - Use the shadow page extension & change the hover over colour

### ISSUE THREAD

**Issue by bluenose1970** [FrDH/mmenu-js#1016]
Hi

Using the Dark Theme, can I change the shadow menu colour as it doesn't show when the Dark Theme is enabled.

Also, is there a way to change the mouseover/hover colour for items?

Thanks

**Comment by FrDH** [comment]
I think this is undocumented (:/), but there's a css variable `--mm-shadow` which you can override:
````css
#my-menu {
   --mm-shadow: 0 0 10px blue !important;
}
````

Hope this helps.
