### ISSUE TITLE
False menu width and scrolling issue in 8.4

### ISSUE THREAD

**Issue by lcsikos** [FrDH/mmenu-js#1090]
If I open https://mmenujs.com/ on the latest version of built-in browser on Samsung S9 device (Samsung Browser V10.2.00.53) the mmenu has false width, and on scrolling down the page the menu is scrolling too.
![Screenshot_20191209-184643_Samsung Internet](https://user-images.githubusercontent.com/33608825/70460185-06486800-1ab6-11ea-9fbf-c28a73620562.jpg)
![Screenshot_20191209-184654_Samsung Internet](https://user-images.githubusercontent.com/33608825/70460251-2aa44480-1ab6-11ea-98eb-81bc9c30fafe.jpg)

**Comment by lcsikos** [comment]
I just saw #1062, but it does not fix the issue on Samsung Browser...

**Comment by FrDH** [comment]
I currently do not have access to a device with a samsung browser, but you could try if fiddling around with the CSS for the HTML and BODY helps.

Try something like this:
````css
html {
   height: 100%;
   overflow: hidden;
}
body {
   height: 100%;
   overflow: auto;
}
````
