### ISSUE TITLE
Question: How to disable sliding in, if navigate on other Main-Page?

### ISSUE THREAD

**Issue by juergen1964** [FrDH/mmenu-js#1112]
Hi there,
since a few days i try out your very nice mmenu. I use it on a TYPO3 website as a Sidemenu - like on the website of the documentation (https://mmenujs.com/). 
So far everything works great and like expected. 
But i got one little problem with the Sidemenu: 
On navigate from one Main-Page to an other Main-Page, the Sidemenu starts always sliding in to open. 
Is there a option (i dont found) to keep the menu opend when navigate to a different Main-Page, like the menu does on the page of de documentation?

I already tryed:

	sidebar: {
                    // sidebar configuration
		expanded: {
                        //false or true
			use: true,
                        //option "remenber"
			initial: "open"
			}
                },

but it looks like that it is not the right setting.
Can You give me a hint? That would be very nice!
Thx and habe a nice day!

**Comment by FrDH** [comment]
I added this CSS to my site:
````css
    @media (min-width: 1024px) {
        width: calc(100% - 60px);
        transform: translate3d(60px, 0, 0);
        transition: none;
    }
    @media (min-width: 1400px) {
        width: calc(100% - 440px);
        transform: translate3d(440px, 0, 0);
        transition: none;
    }
````
Where 1024 is the breakpoint the collapsed sidebar and 1400 for the expanded sidebar.

Hope this helps.
