### ISSUE TITLE
How touch scroll iconbar?

### ISSUE THREAD

**Issue by 438833** [FrDH/mmenu-js#1137]
If there are a lot of icons, then there is a problem.
Also when changing orientation.
Adding -webkit-overflow-scrolling: touch; and overflow: scroll; problem does not solve.

.mm-iconbar__top {
	top: 0;
	padding: 12px 0 0 0;
}

.mm-iconbar__bottom {
	bottom: 0;
	padding: 0 12px 0 0;
}

@media (max-height: 674px){
	.mm-iconbar__top, .mm-iconbar__bottom {
		display: block;
		position: relative;
		padding: 0;
		top: auto;
		bottom: auto;
		width: 70px;
		height: auto;
		min-height: auto;
	}
	.mm-iconbar__top {
		margin: 12px 0 0 0;
	}
}

.mm-iconbar{
    -webkit-overflow-scrolling: touch;
    overflow: scroll;
    overflow-x: hidden;
    overflow-y: auto;
}

Touch does not work on android.

How to be in this?

Thanks in advance.

**Comment by FrDH** [comment]
with the current set-up, I don't the the top and bottom iconbars can ever be aware of eachother. I guess this could be done with a different approach. I'll see if I can get this to work.

Try something like this:
````css
 .mm-iconbar {
    display: flex;
    flex-direction: column;
}
.mm-iconbar__bottom, 
.mm-iconbar__top {
   overflow: auto;
   -webkit-overflow-scrolling: touch;
}
.mm-iconbar__bottom {
   margin-top: auto;
}
````
