### ISSUE TITLE
Unable to disable opening transition

### ISSUE THREAD

**Issue by Lars-** [FrDH/mmenu-js#1195]
Hi, 

For some reason it seems impossible to disable the opening transition. I'm using the sidemenu add-on which works great after some configuration, but I can't disable the opening transition.

The only way I got it to work was by adding this CSS:
```css
* {
  -webkit-transition: none;
  -o-transition: none;
  transition: none !important;
}
```
Which disables all transitions and makes everything ugly. But it works, so it must be something that can be solved with CSS. The weird thing is that I can't find any transitions on the mm-menu classes, so therefore I'm sending this issue.

Could you please explain how to disable it?

Thanks,
Lars Jansen

**Comment by FrDH** [comment]
you should be able to remove the transition by targeting the `.mm-slideout` elements:
````css
.mm-slideout {
   transition: none !important;
}
````

The `!important` is needed to overrule the more specific selectors (like `.mm-wrapper_sidebar-collapsed`).
