### ISSUE TITLE
Navigation is not vertically scrolling in mobile

### ISSUE THREAD

**Issue by maowebsolutions** [FrDH/mmenu-js#1198]
Please take a look at the mobile navigation for [FirstChoiceWellness123.com](https://www.firstchoicewellness123.com/) for example. click to view the services submenu and try to scroll down to see all the items. It's not scrolling all the way down so i can't see all the items under that sub-navigation. I enabled scroll but when I test in mobile it won't scroll with touch.

**Comment by FrDH** [comment]
Not sure if the example is still relevant, but I noticed some added CSS that enable the UL to scroll as well:
````css
.mm-listview {
    list-style: none;
    display: block;
    padding: 0;
    margin: 0;
    overflow: scroll;
    max-height: 100vh;
    height: 100vh;
}
````

Could that be causingf the issue?
