### ISSUE TITLE
Multiline breadcrumb

### ISSUE THREAD

**Issue by valentynpopov** [FrDH/mmenu-js#1209]
Is there a way to a have a multiline breadcrumb, similar to the multiline listitem?

At the moment you get a horizontal scrollbar if the breadcrumb doesn't fit. But that's inconvenient with a multi-level menu because you the closest parent isn't very visible.

**Comment by FrDH** [comment]
Not really. You could add some CSS, but I don't think it'll be very pretty at first.
````css
.mm-navbar__breadcrumbs {
    flex-wrap: wrap;
}
````
