### ISSUE TITLE
Sidebar add-on should not animate menu expansion when page opens with menu expanded

### ISSUE THREAD

**Issue by moujikov** [FrDH/mmenu-js#1269]
Sidebar add-on animates menu expansion on page load, even when the page is being opened wide enough to accommodate expanded (or collapsed) menu right away.

Steps to reproduce: 
1. Open [Sidebar demo](https://mmenujs.com/demo/index.html?demo=sidebar) in a wide window. 
2. Reload the page. 
3. See menu expansion animated on each page load. 

When you are browsing this constant animation gets pretty annoying. As far as I understand, some kind of a workaround has been implemented on mmenujs.com to disable it (disabling the animation until a body class 'docready' is set).

To my mind there should be no animation on page load. Or there should be a configuration option to control this behaviour.

**Comment by Addlersson** [comment]
I am testing mmenu for few new sites and run into this exact problem. It is really annoying to browse website when every page load starts the menu animation (slide from left to right). I also noticed that there is some kind of workaround in mmenu's own site but my skills are not adequate to find out how it is done. I think we do need configuration option for this.

**Comment by FrDH** [comment]
This is due to the javascript only taking effect after the rest of the page has loaded (or at least not immediately when the page starts loading).
For the mmenu website I added this CSS (SCSS):

```css

body:not(.docready) .page {
  @media (min-width: $break_sm) {
    width: calc(100% - 60px);
    transform: translate3d(60px, 0, 0);
    transition: none;
  }

  @media (min-width: $break_xl) {
    width: calc(100% - 440px);
    transform: translate3d(440px, 0, 0);
    transition: none;
  }
}
```

The class "docready" is added to the body right before firing the plugin, so this CSS only applies if the menu was not yet created.
"$break_sm" Is the breakpoint for when the sidebar should be collapsed and "break_xl" for when it should be expanded.

Hope this helps.
