### ISSUE TITLE
Fullscreen 9.2.0

### ISSUE THREAD

**Issue by vguns** [FrDH/mmenu-js#1312]
How set the --mm-size, --mm-min-size and --mm-max-size CSS variables to 100%?

**Comment by FrDH** [comment]
Like this:
````css
:root {
  --mm-size: 100%;
  --mm-min-size: 100%;
  --mm-max-size: 100%;
}
````

You might need to add a more specific selector or `!important` based on the order in which your CSS is loaded.
