### ISSUE TITLE
Menu has no parent container

### ISSUE THREAD

**Issue by thagxt** [FrDH/mmenu-js#1328]
I need to wrap `#menu` in a parent container. With the current approach you can't do any customizations to `#menu` involving `margin` or position `top` `left`  `bottom` . In older versions this was possible, not it is not. I wonder why, and also would like to know how I can add a wrapper. Thanks

```html
<div class="wrapper>
<nav id="menu"></nav>
<a class="mm-wrapper__blocker mm-blocker mm-slideout" id="mm-0"></a>
</div>
```

**Comment by thagxt** [comment]
I forgot, I tried with `insertSelector` but it doesn't not work.

[Here's my code](https://jsfiddle.net/thagxt/cs9ynhdx/1/)

**Comment by FrDH** [comment]
That still should work, except that you'll need to add some CSS for the `div#my-wrapper`:
```css
#my-wrapper {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 100;
}
```
