### ISSUE TITLE
Panels that expand to the right instead of overlaid

### ISSUE THREAD

**Issue by tanc** [FrDH/mmenu-js#1348]
Is it possible to have the child panels expand to the right of their parent instead of overlaid on top?
I'm hoping to figure out a way of having a maximum of three levels expand out to the right as the user clicks through the depth. I would only have this happen if the browser width is sufficient.

Looking at the CSS it looks like it almost possible. I would need to remove the `overflow: hidden` on the wrapper and then adjust the `translate3d` as needed for each depth. The main problem is knowing what depth a child panel is at. They are associated by `data-mm-parent` and `id` but as the panels are at the same DOM depth it doesn't seem possible to position them according to their depth/hierarchy.

Using the example I've positioned them using CSS to demonstrate what I mean:

![image](https://github.com/FrDH/mmenu-js/assets/76320/1df9b5f8-07c4-41e5-ad52-60e111a4df5c)

**Comment by tanc** [comment]
I've found a solution using a combination of the API and some CSS:

https://github.com/FrDH/mmenu-js/assets/76320/c036ee8e-5d98-4d56-afdf-47a6f994f4fb

**Comment by tanc** [comment]
```css
@media screen and (min-width: 1140px) {
  #menu {
    --mm-max-size: 380px;
  }

  #menu .mm-panels {
    overflow: visible;
  }

  #menu .mm-panel {
    --mm-panel-child-offset: 0%;
    --mm-panel-parent-offset: 0%;
    --mm-panel-column2-offset: 100%;
    --mm-panel-column3-offset: 200%;
  }

  #menu .mm-panel[data-depth='0'] {
    z-index: 1000;
  }

  #menu .mm-panel[data-depth='1'] {
    --mm-panel-parent-offset: 100%;
  }

  #menu.mm-menu--opened .mm-panel--opened[data-depth='1'] {
    transform: translate3d(var(--mm-panel-column2-offset), 0, 0);
  }

  #menu.mm-menu--opened .mm-panel--opened[data-depth='1'] ~ .mm-panel {
    transform: translate3d(var(--mm-panel-column2-offset), 0, 0);
  }

  #menu.mm-menu--opened .mm-panel--opened[data-depth='2'] {
    transform: translate3d(var(--mm-panel-column3-offset), 0, 0);
  }

  #menu .mm-panel--parent {
    z-index: 1000;
  }

  #menu .mm-panel--highest {
    z-index: 1;
  }

  #menu:not(.mm-menu--opened) .mm-panel[data-depth='1'],
  #menu:not(.mm-menu--opened) .mm-panel[data-depth='2'] {
    --mm-panel-parent-offset: 0%;
    --mm-panel-offset: 0%;
  }
}
```
