### ISSUE TITLE
Sidebar always slides in from left (animated) with every new page load.

### ISSUE THREAD

**Issue by FSE-DEV** [FrDH/mmenu-js#977]
I enabled a sidebar (in combination with an iconbar). The sidebar slides in animated from the left every time I reload the page or navigate to another page. Didn't configure any animation, didn't find any hint on how to disable this undesired behavior. It drives me nuts. Please help.

**Comment by FrDH** [comment]
Is there an online example I could have a look at?

You could add some CSS to display stuff correctly before the plugin is loaded.
On the documentation site, I use this CSS:
````css
@media (min-width: 400px) {
    #page {
        width: calc( 100% - 60px );
        transform: translate3d(60px,0,0);
        transition: none;
    }
}
@media (min-width: 1000px) {
    #page {
        width: calc(100% - 440px);
        transform: translate3d(440px,0,0);
        transition: none;
    }
}
````
Where:
  - `#page` targets the DIV that wraps all HTML;
  - 400px is the breakpoint for the sidebar (collapsed)
  - 60px is the width for the sidebar (collapsed)
  - 1000px is the breakpoint for the sidebar (expanded)
  - 440px is the width for the sidebar (expanded)

Hope this helps.
